version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    env_file:
        - .env
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - proxy

networks:
  proxy:
    external: true