version: "3.7"
services:
  rabbit1:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - proxy
      - rabbitmq_net

networks:
  rabbitmq_net:
    name: rabbitmq_net
  proxy:
    external: true