version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: db_server
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_data:/docker-entrypoint-initdb.d/:ro
    networks:
      - db_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`phpmyadmin.app.dev`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    ports:
      - 8888:80
    networks:
      - db_net
      - proxy

networks:
  db_net:
    name: db_net
    driver: bridge
  proxy:
    external: true